# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Nagios-Plugin
version:      0.21
version_from: lib/Nagios/Plugin/Functions.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor:               0
    Config::Tiny:                  0
    File::Basename:                0
    File::Spec:                    0
    IO::File:                      0
    Math::Calc::Units:             0
    Params::Validate:              0
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
