---
abstract: 'A family of perl modules to streamline writing Nagios'
author:
  - 'Monitoring Plugin Development Team <team@monitoring-plugins.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Plugin
no_index:
  directory:
    - t
    - inc
requires:
  Monitoring::Plugin: 0
  Test::More: 0.62
  base: 0
version: 0.37
