--- #YAML:1.0
name:                Nagios-Plugin
version:             0.23
abstract:            A family of perl modules to streamline writing Nagios 
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3101
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor:               0
    Config::Tiny:                  0
    File::Basename:                0
    File::Spec:                    0
    IO::File:                      0
    Math::Calc::Units:             0
    Params::Validate:              0
    Test::More:                    0.62
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Nagios Plugin Development Team <nagiosplug-devel@lists.sourceforge.net>
